services:
  aviary:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      RMAPI_HOST: "${RMAPI_HOST}"
    volumes:
      - type: bind
        source: ./rmapi.conf
        target: /root/.config/rmapi/rmapi.conf
    restart: unless-stopped
