services:
  aviary:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    tty: true
    stdin_open: true
    environment:
      PDF_DIR: /app/pdfs
      RMAPI_HOST: "${RMAPI_HOST}"
    volumes:
      - ./pdfs:/app/pdfs
      - ./rmapi.conf:/root/.config/rmapi/rmapi.conf
