services:
  aviary:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      RMAPI_HOST: "${RMAPI_HOST}"
      # Optional authentication (remove # to enable):
      # AUTH_USERNAME: "${AUTH_USERNAME}"
      # AUTH_PASSWORD: "${AUTH_PASSWORD}"
      # API_KEY: "${API_KEY}"
      DRY_RUN: "true"
    volumes:
      - type: bind
        source: ./rmapi.conf
        target: /root/.config/rmapi/rmapi.conf
      - type: bind
        source: ./pdfs
        target: /app/pdfs
    restart: unless-stopped
